services:
  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: zenycero
      POSTGRES_PASSWORD: zenycero
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - zipkin
  #rabbitmq:
  #  image: rabbitmq:3.8-management-alpine
  #  container_name: 'rabbitmq'
  #  ports:
  #    - 5673:5672
  #    - 15673:15672
  #  volumes:
  #    - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
  #    - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  #  networks:
  #    - rabbitmq

networks:
  #rabbitmq:
  #  driver: bridge
  postgres:
    driver: bridge
  zipkin:
    driver: bridge

volumes:
  postgres:
  pgadmin:
