server:
  port: 8095

spring:
  application:
    name: security
  config:
    import: optional:configserver:http://localhost:8888

#logging:
#  level:
#    org.springframework.security.web: DEBUG



