eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8222
spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student
          uri: lb://STUDENT
          predicates:
            - Path=/api/v1/students/**
          filters:
            - AuthenticationFilter
        - id: school
          uri: lb://SCHOOL
          predicates:
            - Path=/api/v1/schools/**
          filters:
            - AuthenticationFilter
        - id: security
          uri: lb://SECURITY
          predicates:
            - Path=/auth/**

management:
  tracing:
    sampling:
      probability: 1.0
